name: hashcash_dart
description: A hashcash proof of work implementation for Dart and Flutter
version: 1.0.1
homepage: https://github.com/konstantinullrich
repository: https://github.com/konstantinullrich/hashcash
issue_tracker: https://github.com/konstantinullrich/hashcash/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  crypto: ^3.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
