name: hashcash_dart
description: A hashcash proof of work implementation for Dart and Flutter
version: 1.1.0
homepage: https://github.com/konstantinullrich
repository: https://github.com/konstantinullrich/hashcash
issue_tracker: https://github.com/konstantinullrich/hashcash/issues

environment:
  sdk: ^3.0.6

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
