name: hashcash_dart
description: A hashcash proof of work implementation for Dart and Flutter
version: 0.1.0
homepage: https://github.com/konstantinullrich
repository: https://github.com/konstantinullrich/hashcash
issue_tracker: https://github.com/konstantinullrich/hashcash/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: ^2.1.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
